#!/usr/bin/env bash
#
# Non-blocking layout-length report (ut-docs#297): lists every key whose
# German value is materially longer (>40% by character count) than core's
# English value, sorted by ratio descending, as a markdown table on
# stdout. A byte-length heuristic cannot verify actual rendered layout, so
# this is deliberately NOT a CI gate -- it is the spot-check list a
# reviewer/tester uses to drive the sale screen at 10-inch/kiosk sizes and
# eyeball the highest-risk strings. Keys whose dot-path suggests a small
# fixed-width UI element (a .button/.btn/.tab/.action/.label/.col/.chip
# segment, or a namespace rendered in fixed-width chrome: tender.*, nav.*,
# status.*, common.*, osk.*, basket.*, sync.*) are marked "yes" in the
# fixed-width? column -- check those first.
#
# Usage:
#   UT_CORE_EN_JSON=<path> scripts/report-length-flags.sh > docs/de-length-flags.md
# Core's en.json is resolved exactly like check-key-drift.sh does:
# UT_CORE_EN_JSON for a local file, else fetched from
# UT_CORE_EN_URL/CORE_EN_URL.
set -euo pipefail

# Resolve UT_CORE_EN_JSON against the CALLER's cwd before we cd (same rule
# as check-key-drift.sh).
if [ -n "${UT_CORE_EN_JSON:-}" ]; then
    case "$UT_CORE_EN_JSON" in
        /*) ;;
        *) UT_CORE_EN_JSON="$(pwd)/${UT_CORE_EN_JSON}" ;;
    esac
fi

cd "$(dirname "$0")/.."

CORE_EN_URL="${UT_CORE_EN_URL:-https://raw.githubusercontent.com/universaltill/universal-till/main/web/locales/en.json}"
DE_LOCALE="locales/de.json"

CORE_EN_JSON=""
CORE_TMP=""
cleanup() {
    if [ -n "$CORE_TMP" ]; then
        rm -f "$CORE_TMP"
    fi
}
trap cleanup EXIT INT TERM

if [ -n "${UT_CORE_EN_JSON:-}" ]; then
    CORE_EN_JSON="${UT_CORE_EN_JSON}"
    if [ ! -f "$CORE_EN_JSON" ]; then
        echo "report-length-flags: UT_CORE_EN_JSON=${CORE_EN_JSON} does not exist" >&2
        exit 1
    fi
else
    CORE_TMP="$(mktemp)"
    CORE_EN_JSON="$CORE_TMP"
    if ! curl -fsSL "$CORE_EN_URL" -o "$CORE_EN_JSON"; then
        echo "report-length-flags: FAILED to fetch core base locale from ${CORE_EN_URL}" >&2
        echo "report-length-flags: set UT_CORE_EN_JSON=<path> to run against a local checkout." >&2
        exit 1
    fi
fi

python3 - "$CORE_EN_JSON" "$DE_LOCALE" <<'PY'
import json
import sys

core_path, de_path = sys.argv[1:3]
core = json.load(open(core_path))
de = json.load(open(de_path))

THRESHOLD = 1.4  # de is "materially longer" above +40% by character count

# Dot-path segments that suggest a small fixed-width UI element (buttons,
# tabs, chips, column headers, short labels).
RISK_SEGMENTS = {"button", "btn", "tab", "action", "label", "col", "chip", "short"}
# Top-level namespaces rendered in fixed-width chrome (sale-screen tender
# panel, nav bar, status chips, shared small buttons, on-screen keyboard,
# basket panel, sync chips).
RISK_NAMESPACES = {"tender", "nav", "status", "common", "osk", "basket", "sync"}

def fixed_width_risk(key):
    segs = key.split(".")
    if segs[0] in RISK_NAMESPACES:
        return True
    return any(s in RISK_SEGMENTS for s in segs)

rows = []
for k in sorted(set(core) & set(de)):
    en_len, de_len = len(core[k]), len(de[k])
    if en_len == 0:
        continue
    ratio = de_len / en_len
    if ratio > THRESHOLD:
        rows.append((ratio, k, en_len, de_len))

rows.sort(key=lambda r: (-r[0], r[1]))

print("# German string-length flags (layout spot-check list)")
print()
print("Generated by `scripts/report-length-flags.sh` — non-blocking, not a CI")
print("gate. Every key below has a German value more than 40% longer (by")
print("character count) than core's English value, sorted by ratio descending.")
print("**fixed-width? = yes** marks keys whose dot-path suggests a small")
print("fixed-width UI element (button/tab/chip/column-header labels, or the")
print("tender/nav/status/common/osk/basket/sync chrome) — drive the sale")
print("screen at 10-inch/kiosk sizes and spot-check those first.")
print()
print(f"{len(rows)} flagged of {len(set(core) & set(de))} translated keys.")
print()
print("| key | en len | de len | ratio | fixed-width? |")
print("|---|---:|---:|---:|:---:|")
for ratio, k, en_len, de_len in rows:
    risk = "yes" if fixed_width_risk(k) else ""
    print(f"| `{k}` | {en_len} | {de_len} | {ratio:.2f} | {risk} |")
PY
